spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/easyecommerce
    username: postgres
    password: 44815602
  name: easyecommerce
  context-path: /easyecommerce

security:
  jwt:
    expiration-minutes: 30
    secret-key: ZWwgc29sIHNlIGNhc2EgY29uIGxhIGx1bmEgeSBzYXR1cm8gZ3VhcmRhIGxvcyBhbmlsbG9z


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8081